<a href="https://colab.research.google.com/github/MaxVieiraSantiago/Meus-Estudos/blob/master/UDEMY_Amostragem_Simples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importando as biliotecas necess√°rias
import pandas as pd
import numpy as np

In [2]:
# Obtendo o dataset
url = 'https://raw.githubusercontent.com/MaxVieiraSantiago/Machine-Learning-Algorithms/master/Dataset/Iris.csv'

dados = pd.read_csv( url )

In [3]:
# Quantidade de linhas e colunas
dados.shape

(150, 6)

In [4]:
# Visualizando alguns registros
dados.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
# Mudan√ßa da semente aleat√≥ria rand√¥mica para gerar os resultados em v√°rias execu√ß√µes
np.random.seed( 2345 )

In [23]:
# 150 ( s√£o 150 linhas no dataset ) amostras entre 0 e 1 com reposi√ß√£o, probabilidades equivalentes
amostra = np.random.choice( a=[0,1], size=150, replace=True, p=[0.7, 0.3] )
# Hiperpar√¢metros -> ( a= espa√ßo amostral ), ( size= tamanho, quantidade de elementos da amostra ), 
#                    ( replace= com reposi√ß√£o, quando gerar o 0 ou 1, informa que pode gerar novamente, sen√£o, gera 0 por exemplo e depois n√£o pode mais gerar...teremos problema ), 
#                    ( p= probabilidades de gera√ß√£o de cada valor, n√£o quer dizer percentual dos valores mas a probabilidade daquela valor ser gerado )

In [8]:
# Verificar o tamanho da amostra
len( amostra )

150

In [14]:
# Criar o campo amostra no dataset com as amostras criadas rand√¥micamente
dados['amostra'] = amostra
dados

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,amostra
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,1
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,1
146,147,6.3,2.5,5.0,1.9,Iris-virginica,1
147,148,6.5,3.0,5.2,2.0,Iris-virginica,0
148,149,6.2,3.4,5.4,2.3,Iris-virginica,0
149,150,5.9,3.0,5.1,1.8,Iris-virginica,1

In [21]:
# Verificar tamanho da amostra por valores
print( len( amostra[ amostra == 1 ] ) )
print( len( amostra[ amostra == 0 ] ) )

45
105

In [15]:
dados_final = dados.loc[ amostra == 0 ]
dados_final

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,amostra
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
5,6,5.4,3.9,1.7,0.4,Iris-setosa,0
...,...,...,...,...,...,...,...
140,141,6.7,3.1,5.6,2.4,Iris-virginica,0
143,144,6.8,3.2,5.9,2.3,Iris-virginica,0
144,145,6.7,3.3,5.7,2.5,Iris-virginica,0
147,148,6.5,3.0,5.2,2.0,Iris-virginica,0
148,149,6.2,3.4,5.4,2.3,Iris-virginica,0

In [24]:
dados2 = dados[ amostra == 0]
dados2

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,amostra
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
5,6,5.4,3.9,1.7,0.4,Iris-setosa,0
6,7,4.6,3.4,1.4,0.3,Iris-setosa,0
...,...,...,...,...,...,...,...
141,142,6.9,3.1,5.1,2.3,Iris-virginica,1
142,143,5.8,2.7,5.1,1.9,Iris-virginica,1
143,144,6.8,3.2,5.9,2.3,Iris-virginica,0
147,148,6.5,3.0,5.2,2.0,Iris-virginica,0
149,150,5.9,3.0,5.1,1.8,Iris-virginica,1